s=set()

n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())
n=input("Enter your number: ")
s.add(int())

print(s)